import Features from "./Features";
import { Security } from "@mui/icons-material";

const featuresItems = [
  {
    title: "Proactive blocklist tracking",
    description:
      "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.",
    icon: <Security />,
  },
  {
    title: "Proactive blocklist tracking",
    description:
      "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.",
    icon: <Security />,
  },
  {
    title: "Proactive blocklist tracking",
    description:
      "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.",
    icon: <Security />,
  },
  {
    title: "Proactive blocklist tracking",
    description:
      "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.",
    icon: <Security />,
  },
  {
    title: "Proactive blocklist tracking",
    description:
      "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.",
    icon: <Security />,
  },
  {
    title: "Proactive blocklist tracking",
    description:
      "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.",
    icon: <Security />,
  },
];

const FeaturesHome = () => {
  return <Features title="Section" items={featuresItems} />;
};

export default FeaturesHome;
